package com.ghosttools.jet625;

import android.app.Activity;
import android.os.Bundle;
import android.content.Intent;
import android.net.Uri;
import android.graphics.*;
import android.view.*;
import android.widget.*;
import android.content.Context;
import java.io.*;
import java.nio.charset.StandardCharsets;
import java.util.*;

public class MainActivity extends Activity {
    private static final int REQ_OPEN = 10;
    private static final int REQ_SAVE = 11;
    CadView cad;
    TextView status;
    Spinner layerSpinner;
    DxfDoc doc = new DxfDoc();
    String activeLayer = "0";
    Mode mode = Mode.SELECT;
    enum Mode { SELECT, PAN, LINE, RECTANGLE, CIRCLE }

    @Override public void onCreate(Bundle b) {
        super.onCreate(b);
        LinearLayout root = new LinearLayout(this);
        root.setOrientation(LinearLayout.VERTICAL);
        root.setBackgroundColor(Color.BLACK);
        HorizontalScrollView scroll = new HorizontalScrollView(this);
        LinearLayout bar = new LinearLayout(this);
        bar.setPadding(4,4,4,4);
        scroll.addView(bar);
        addBtn(bar,"Open",v->openDxf()); addBtn(bar,"Export",v->exportDxf()); addBtn(bar,"Fit",v->cad.fit());
        addBtn(bar,"Select",v->setMode(Mode.SELECT)); addBtn(bar,"Pan",v->setMode(Mode.PAN)); addBtn(bar,"Line",v->setMode(Mode.LINE));
        addBtn(bar,"Rect",v->setMode(Mode.RECTANGLE)); addBtn(bar,"Circle",v->setMode(Mode.CIRCLE)); addBtn(bar,"Delete",v->{cad.deleteSelected(); refresh();});
        addBtn(bar,"Chain Check",v->{cad.chainCheck(); refresh();}); addBtn(bar,"Clear Check",v->{cad.openEnds.clear(); cad.invalidate(); refresh();});
        addBtn(bar,"Apply Layer",v->{cad.applyLayer(activeLayer); refresh();});
        layerSpinner = new Spinner(this); bar.addView(layerSpinner,new LinearLayout.LayoutParams(dp(180),dp(48)));
        layerSpinner.setOnItemSelectedListener(new AdapterView.OnItemSelectedListener(){ public void onItemSelected(AdapterView<?> p,View v,int pos,long id){activeLayer=String.valueOf(p.getItemAtPosition(pos));} public void onNothingSelected(AdapterView<?> p){} });
        cad = new CadView(this); cad.main=this; cad.doc=doc;
        status = new TextView(this); status.setTextColor(Color.WHITE); status.setTextSize(13); status.setPadding(8,4,8,4);
        root.addView(scroll,new LinearLayout.LayoutParams(-1,dp(56))); root.addView(cad,new LinearLayout.LayoutParams(-1,0,1)); root.addView(status,new LinearLayout.LayoutParams(-1,dp(48)));
        setContentView(root); refreshLayers(); refresh();
    }
    void addBtn(LinearLayout bar,String t,View.OnClickListener l){ Button b=new Button(this); b.setText(t); b.setAllCaps(false); b.setTextSize(12); b.setTextColor(Color.WHITE); b.setBackgroundColor(Color.rgb(22,22,22)); b.setOnClickListener(l); bar.addView(b,new LinearLayout.LayoutParams(-2,dp(48))); }
    int dp(int v){return (int)(v*getResources().getDisplayMetrics().density+.5f);} void setMode(Mode m){mode=m; cad.mode=m; cad.pending.clear(); refresh();}
    void refresh(){status.setText("Mode: "+mode+"   Layer: "+activeLayer+"   Entities: "+doc.entities.size()+"   Open ends: "+cad.openEnds.size()); cad.invalidate();}
    void refreshLayers(){ArrayList<String> n=new ArrayList<>(doc.layers.keySet()); Collections.sort(n); ArrayAdapter<String>a=new ArrayAdapter<>(this,android.R.layout.simple_spinner_dropdown_item,n); layerSpinner.setAdapter(a); layerSpinner.setSelection(Math.max(0,n.indexOf(activeLayer)));}
    void openDxf(){Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT); i.addCategory(Intent.CATEGORY_OPENABLE); i.setType("*/*"); startActivityForResult(i,REQ_OPEN);} void exportDxf(){Intent i=new Intent(Intent.ACTION_CREATE_DOCUMENT); i.addCategory(Intent.CATEGORY_OPENABLE); i.setType("application/dxf"); i.putExtra(Intent.EXTRA_TITLE,"jet625_export.dxf"); startActivityForResult(i,REQ_SAVE);}
    @Override protected void onActivityResult(int r,int ok,Intent data){super.onActivityResult(r,ok,data); if(ok!=RESULT_OK||data==null||data.getData()==null)return; try{Uri u=data.getData(); if(r==REQ_OPEN){doc=Dxf.read(read(u)); cad.doc=doc; cad.fit(); refreshLayers(); Toast.makeText(this,"DXF opened",0).show();} else {write(u,Dxf.write(doc)); Toast.makeText(this,"DXF exported",0).show();} refresh();}catch(Exception e){Toast.makeText(this,"Error: "+e.getMessage(),1).show();}}
    String read(Uri u)throws IOException{InputStream is=getContentResolver().openInputStream(u); ByteArrayOutputStream b=new ByteArrayOutputStream(); byte[] buf=new byte[8192]; int n; while((n=is.read(buf))>0)b.write(buf,0,n); is.close(); return new String(b.toByteArray(),StandardCharsets.UTF_8);} void write(Uri u,String s)throws IOException{OutputStream os=getContentResolver().openOutputStream(u,"wt"); os.write(s.getBytes(StandardCharsets.US_ASCII)); os.close();}

    static class Pt{double x,y; Pt(double x,double y){this.x=x;this.y=y;}}
    static class Ent{String type,layer="0"; int color=256; double x1,y1,x2,y2,cx,cy,r,start,end; ArrayList<Pt> pts=new ArrayList<>(); boolean closed;}
    static class DxfDoc{LinkedHashMap<String,Integer> layers=new LinkedHashMap<>(); ArrayList<Ent> entities=new ArrayList<>(); DxfDoc(){layers.put("0",7);layers.put("CUTOUT",5);layers.put("EASE",3);layers.put("SEAM",1);layers.put("WALL",34);layers.put("OtherEDGE",4);layers.put("Mill",30);layers.put("STOVEorFRIDGE",200);} int color(Ent e){return e.color==256?(layers.containsKey(e.layer)?layers.get(e.layer):7):e.color;}}
    static int aci(int c){switch(c){case 1:return Color.RED;case 2:return Color.YELLOW;case 3:return Color.GREEN;case 4:return Color.CYAN;case 5:return Color.BLUE;case 30:return Color.rgb(139,69,19);case 34:return Color.rgb(168,90,26);case 200:return Color.rgb(255,102,204);default:return Color.WHITE;}}
    static String clean(String s){if(s==null||s.trim().isEmpty())return "0"; String u=s.trim().toUpperCase(Locale.US); if(u.equals("OTHEREDGE"))return "OtherEDGE"; if(u.equals("MILL"))return "Mill"; if(u.equals("STOVEORFRIDGE"))return "STOVEorFRIDGE"; return u;}
    static class Dxf{static class Pair{int c;String v;Pair(int c,String v){this.c=c;this.v=v;}} static ArrayList<Pair> pairs(String t){String[]l=t.replace("\r","\n").split("\n");ArrayList<Pair>p=new ArrayList<>();for(int i=0;i+1<l.length;i+=2)try{p.add(new Pair(Integer.parseInt(l[i].trim()),l[i+1].trim()));}catch(Exception e){}return p;} static double d(String s){try{return Double.parseDouble(s);}catch(Exception e){return 0;}}
        static DxfDoc read(String t){DxfDoc doc=new DxfDoc();ArrayList<Pair>p=pairs(t);boolean ent=false,old=false;Ent e=null;Pt v=null;for(Pair q:p){if(q.c==2&&q.v.equals("ENTITIES")){ent=true;continue;} if(!ent)continue; if(q.c==0){if(old&&v!=null&&e!=null){e.pts.add(v);v=null;} if(q.v.equals("ENDSEC")){if(e!=null)doc.entities.add(e);break;} if(q.v.equals("LINE")||q.v.equals("CIRCLE")||q.v.equals("ARC")){if(e!=null)doc.entities.add(e);e=new Ent();e.type=q.v;old=false;continue;} if(q.v.equals("LWPOLYLINE")||q.v.equals("POLYLINE")){if(e!=null)doc.entities.add(e);e=new Ent();e.type="POLYLINE";old=q.v.equals("POLYLINE");continue;} if(q.v.equals("VERTEX")&&old){v=new Pt(0,0);continue;} if(q.v.equals("SEQEND")){if(e!=null){doc.entities.add(e);e=null;}old=false;continue;}} if(e==null)continue; if(old&&v!=null){if(q.c==10)v.x=d(q.v); if(q.c==20)v.y=d(q.v); continue;} if(q.c==8){e.layer=clean(q.v);doc.layers.put(e.layer,doc.layers.containsKey(e.layer)?doc.layers.get(e.layer):7);} if(q.c==62)try{e.color=Math.abs(Integer.parseInt(q.v));}catch(Exception ex){} if(e.type.equals("POLYLINE")){if(q.c==70)e.closed=((int)d(q.v)&1)!=0; if(q.c==10)e.pts.add(new Pt(d(q.v),0)); if(q.c==20&&e.pts.size()>0)e.pts.get(e.pts.size()-1).y=d(q.v);} else {if(q.c==10)e.x1=e.cx=d(q.v); if(q.c==20)e.y1=e.cy=d(q.v); if(q.c==11)e.x2=d(q.v); if(q.c==21)e.y2=d(q.v); if(q.c==40)e.r=d(q.v); if(q.c==50)e.start=d(q.v); if(q.c==51)e.end=d(q.v);}} return doc;}
        static String f(double x){String s=String.format(Locale.US,"%.6f",x);while(s.contains(".")&&s.endsWith("0"))s=s.substring(0,s.length()-1);return s.endsWith(".")?s.substring(0,s.length()-1):s;} static void a(StringBuilder s,int c,Object v){s.append(c).append('\n').append(v).append('\n');}
        static String write(DxfDoc doc){StringBuilder s=new StringBuilder();a(s,0,"SECTION");a(s,2,"HEADER");a(s,9,"$ACADVER");a(s,1,"AC1009");a(s,0,"ENDSEC");a(s,0,"SECTION");a(s,2,"TABLES");a(s,0,"TABLE");a(s,2,"LAYER");a(s,70,doc.layers.size());for(String l:doc.layers.keySet()){a(s,0,"LAYER");a(s,2,l);a(s,70,0);a(s,62,doc.layers.get(l));a(s,6,"CONTINUOUS");}a(s,0,"ENDTAB");a(s,0,"ENDSEC");a(s,0,"SECTION");a(s,2,"ENTITIES");for(Ent e:doc.entities){int c=doc.color(e); if(e.type.equals("LINE")){a(s,0,"LINE");a(s,8,e.layer);a(s,62,c);a(s,10,f(e.x1));a(s,20,f(e.y1));a(s,11,f(e.x2));a(s,21,f(e.y2));} else if(e.type.equals("CIRCLE")){a(s,0,"CIRCLE");a(s,8,e.layer);a(s,62,c);a(s,10,f(e.cx));a(s,20,f(e.cy));a(s,40,f(e.r));} else if(e.type.equals("ARC")){a(s,0,"ARC");a(s,8,e.layer);a(s,62,c);a(s,10,f(e.cx));a(s,20,f(e.cy));a(s,40,f(e.r));a(s,50,f(e.start));a(s,51,f(e.end));} else {a(s,0,"POLYLINE");a(s,8,e.layer);a(s,66,1);a(s,70,e.closed?1:0);a(s,62,c);for(Pt p:e.pts){a(s,0,"VERTEX");a(s,8,e.layer);a(s,10,f(p.x));a(s,20,f(p.y));}a(s,0,"SEQEND");}}a(s,0,"ENDSEC");a(s,0,"EOF");return s.toString();}}
    static class CadView extends View{MainActivity main;DxfDoc doc;Paint p=new Paint(1);float scale=1,ox=0,oy=0,lastX,lastY;Mode mode=Mode.SELECT;int sel=-1;ArrayList<Pt>pending=new ArrayList<>(),openEnds=new ArrayList<>(); CadView(Context c){super(c);setBackgroundColor(Color.BLACK);} PointF ws(Pt q){return new PointF((float)(q.x*scale+ox),(float)(getHeight()-q.y*scale+oy));} Pt sw(float x,float y){return new Pt((x-ox)/scale,(getHeight()+oy-y)/scale);} @Override protected void onDraw(Canvas c){p.setStyle(Paint.Style.STROKE);p.setStrokeWidth(1);p.setColor(Color.rgb(25,25,25));for(float x=ox%50;x<getWidth();x+=50)c.drawLine(x,0,x,getHeight(),p);for(float y=oy%50;y<getHeight();y+=50)c.drawLine(0,y,getWidth(),y,p); if(doc!=null)for(int i=0;i<doc.entities.size();i++)draw(c,doc.entities.get(i),i==sel);p.setColor(Color.GREEN);p.setStrokeWidth(4);for(Pt q:openEnds){PointF s=ws(q);c.drawCircle(s.x,s.y,14,p);}}
        void draw(Canvas c,Ent e,boolean on){p.setColor(on?Color.rgb(255,140,0):aci(doc.color(e)));p.setStrokeWidth(on?5:3);if(e.type.equals("LINE")){PointF a=ws(new Pt(e.x1,e.y1)),b=ws(new Pt(e.x2,e.y2));c.drawLine(a.x,a.y,b.x,b.y,p);}else if(e.type.equals("CIRCLE")){PointF a=ws(new Pt(e.cx,e.cy));c.drawCircle(a.x,a.y,(float)Math.abs(e.r*scale),p);}else if(e.type.equals("ARC")){RectF r=new RectF(ws(new Pt(e.cx-e.r,e.cy+e.r)).x,ws(new Pt(e.cx-e.r,e.cy+e.r)).y,ws(new Pt(e.cx+e.r,e.cy-e.r)).x,ws(new Pt(e.cx+e.r,e.cy-e.r)).y);c.drawArc(r,(float)-e.end,(float)(e.end-e.start),false,p);}else if(e.pts.size()>1){Path path=new Path();PointF a=ws(e.pts.get(0));path.moveTo(a.x,a.y);for(int i=1;i<e.pts.size();i++){PointF b=ws(e.pts.get(i));path.lineTo(b.x,b.y);}if(e.closed)path.close();c.drawPath(path,p);}}
        @Override public boolean onTouchEvent(MotionEvent ev){float x=ev.getX(),y=ev.getY();if(ev.getAction()==0){lastX=x;lastY=y;return true;}if(ev.getAction()==2){if(mode==Mode.PAN||mode==Mode.SELECT){ox+=x-lastX;oy+=y-lastY;lastX=x;lastY=y;invalidate();}return true;}if(ev.getAction()==1){Pt w=sw(x,y); if(mode==Mode.LINE){if(pending.isEmpty())pending.add(w);else{Ent e=new Ent();e.type="LINE";e.layer=main.activeLayer;e.x1=pending.get(0).x;e.y1=pending.get(0).y;e.x2=w.x;e.y2=w.y;doc.entities.add(e);pending.clear();}}else if(mode==Mode.RECTANGLE){if(pending.isEmpty())pending.add(w);else{Pt a=pending.get(0);Ent e=new Ent();e.type="POLYLINE";e.layer=main.activeLayer;e.closed=true;e.pts.add(new Pt(a.x,a.y));e.pts.add(new Pt(w.x,a.y));e.pts.add(new Pt(w.x,w.y));e.pts.add(new Pt(a.x,w.y));doc.entities.add(e);pending.clear();}}else if(mode==Mode.CIRCLE){if(pending.isEmpty())pending.add(w);else{Pt a=pending.get(0);Ent e=new Ent();e.type="CIRCLE";e.layer=main.activeLayer;e.cx=a.x;e.cy=a.y;e.r=Math.hypot(w.x-a.x,w.y-a.y);doc.entities.add(e);pending.clear();}}else if(mode==Mode.SELECT){sel=find(x,y);}main.refresh();return true;}return true;}
        int find(float x,float y){double best=25;int bi=-1;for(int i=0;i<doc.entities.size();i++){Ent e=doc.entities.get(i);ArrayList<Pt>pts=points(e);for(Pt q:pts){PointF s=ws(q);double d=Math.hypot(s.x-x,s.y-y);if(d<best){best=d;bi=i;}}}return bi;} ArrayList<Pt>points(Ent e){ArrayList<Pt>a=new ArrayList<>();if(e.type.equals("LINE")){a.add(new Pt(e.x1,e.y1));a.add(new Pt(e.x2,e.y2));}else if(e.type.equals("CIRCLE")){a.add(new Pt(e.cx,e.cy));}else a.addAll(e.pts);return a;} void deleteSelected(){if(sel>=0&&sel<doc.entities.size()){doc.entities.remove(sel);sel=-1;}} void applyLayer(String l){if(sel>=0){doc.entities.get(sel).layer=l;doc.layers.put(l,doc.layers.containsKey(l)?doc.layers.get(l):7);}} void fit(){if(doc==null||doc.entities.isEmpty()){scale=1;ox=80;oy=-80;invalidate();return;}double minx=1e9,miny=1e9,maxx=-1e9,maxy=-1e9;for(Ent e:doc.entities)for(Pt q:points(e)){minx=Math.min(minx,q.x);miny=Math.min(miny,q.y);maxx=Math.max(maxx,q.x);maxy=Math.max(maxy,q.y);}scale=(float)Math.min(getWidth()/Math.max(1,maxx-minx+20),getHeight()/Math.max(1,maxy-miny+20));ox=(float)(20-minx*scale);oy=(float)(-20+miny*scale);invalidate();} void chainCheck(){openEnds.clear();HashMap<String,Integer>m=new HashMap<>();HashMap<String,Pt>pts=new HashMap<>();for(Ent e:doc.entities)if(e.layer.equals("0")){ArrayList<Pt>a=points(e);if(a.size()>1&&!e.closed){Pt p1=a.get(0),p2=a.get(a.size()-1);String k1=Math.round(p1.x*1000)+","+Math.round(p1.y*1000),k2=Math.round(p2.x*1000)+","+Math.round(p2.y*1000);m.put(k1,m.getOrDefault(k1,0)+1);m.put(k2,m.getOrDefault(k2,0)+1);pts.put(k1,p1);pts.put(k2,p2);}}for(String k:m.keySet())if(m.get(k)==1)openEnds.add(pts.get(k));invalidate();}}
}
